package com.app.weather.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.app.weather.mapper.LocalDateConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Data
@Builder(toBuilder = true)
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "SensorDataInfo")
public class SensorDataInfo {
    @DynamoDBHashKey(attributeName = "uuid")
    @DynamoDBAutoGeneratedKey
    private String uuid;
    @DynamoDBAttribute(attributeName = "sensorId")
    @DynamoDBRangeKey
    private String sensorId;
    @DynamoDBAttribute(attributeName = "tempData")
    private String tempData;

    @DynamoDBAttribute(attributeName = "humidityData")
    private String humidityData;
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    @DynamoDBAttribute(attributeName = "createTs")
    private LocalDate createTs;

}
